name: production

on: [push]

permissions:
    contents: read
    id-token: write


jobs:
  test:
    runs-on: ubuntu-20.04
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build app for test
        uses: ./.github/actions/build
        with:
            APP_ENV: ${{ secrets.PRO_APP_ENV }}
            APP_KEY: ${{ secrets.PRO_APP_KEY }}
            APP_ENV_NAME: ".env.prd"
            COMPOSER_INSTALL_NO_DEV: "false"
            APP_URL: https://allabout-ogawa-cloudrun-q3kkj36qnq-uw.a.run.app/
      

      - name: wait for phpunit
        run: |
            docker
      - name: phpunit
        id: phpunit
        run: |
            if [ ! -d ./test-results ]; then mkdir ./test-results; fi
            ./vendor/bin/phpunit -d memory_limit=1G --stderr
        working-directory: src



  deploy:
    runs-on: ubuntu-20.04
    needs: test
    if: contains(github.head_ref, 'release') || github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build app for deploy
        uses: ./.github/actions/build
        with:
          APP_ENV: ${{ secrets.PRO_APP_ENV }}
          APP_KEY: ${{ secrets.PRO_APP_KEY }}
          APP_ENV_NAME: ".env.prd"
          COMPOSER_INSTALL_NO_DEV: "true"
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          MAIL_FROM_ADDRESS: ${{ secrets.MAIL_FROM_ADDRESS }}
          MAIL_TO_CONTACT_ADDRESS: ${{ secrets.MAIL_TO_CONTACT_ADDRESS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Authorize Docker push
        run: |
          echo '${{ secrets.GKE_SERVICE_ACCOUNT_KEY }}' > allabout-kubernetes-service-account.json
          gcloud auth activate-service-account --key-file allabout-kubernetes-service-account.json
          gcloud auth configure-docker us-west1-docker.pkg.dev
      - name: setup docker env
        run: |
          echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ github.sha }}-${{ github.run_number }}" >> $GITHUB_ENV
      - name: docker build and push
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          push: true
          file: cd/${{ secrets.PRO_APP_ENV }}/php/Dockerfile
          build-args: |
            APP_ENV=${{ secrets.PRO_APP_ENV }}
            APP_PATH=/var/www/app
          tags: |
            us-west1-docker.pkg.dev/o-taiji/${{ env.REPOSITORY_NAME }}/app:latest
            us-west1-docker.pkg.dev/o-taiji/${{ env.REPOSITORY_NAME }}/app:${{ env.IMAGE_TAG }}
      - name: set env
        run: | 
            echo "DEPLOYMENT_CONTAINER_IMAGE=us-west1-docker.pkg.dev/o-taiji/${{ env.REPOSITORY_NAME }}/app:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV
            echo "CERT_DOMAIN=webhook.ogawa.allabout.oootaiji.com" >> $GITHUB_ENV
      - name: auth gke
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/246684855382/locations/global/workloadIdentityPools/allabout-oidc/providers/github-actions'
          service_account: allabout@o-taiji.iam.gserviceaccount.com
      - name: deploy cloud run
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: ${{ env.REPOSITORY_NAME }}
          image: ${{ env.DEPLOYMENT_CONTAINER_IMAGE }}
          region: us-west1

